name: Github actions
run-name: ${{ github.actor }} is testing out github actions
on: [push]

jobs:
    exploration:
      runs-on: ubuntu-latest
      steps:
        - run: echo "started testing"
        - name: listing files in repository
          run: ls ${{github.workspace }}
        - run: echo" job status---- ${{ job.status}}"
